{% set name = "shiny" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/shiny-{{ version }}.tar.gz
  sha256: 0a29065a4fb3e3971b310e710bc406357667f44d1611545cf366f595a7f16a93

build:
  number: 0
  noarch: python
  entry_points:
    - shiny = shiny._main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - appdirs >=1.4.4
    - asgiref >=3.5.2
    - click >=8.0.3
    - htmltools >=0.2.1
    - linkify-it-py >=1.0
    - markdown-it-py >=1.1.0
    - mdit-py-plugins >=0.3.0
    - python-multipart
    - starlette >=0.17.1
    - typing-extensions >=4.0.1
    - uvicorn >=0.16.0
    - websockets >=10.0
    ## DONOT REMOVE THESE LINES
    # grayskull utility generated some
    # of the dependencies, but they are
    # not used as is or just dropped altogether.
    # # - contextvars >=2.4 [only necessary for python>=3,<3.7]

test:
  imports:
    - shiny
  commands:
    # Commenting out pip check as it compains about
    # not finding contextvars (which is only necessary
    # for python<3.7)
    # - pip check
    - shiny --help
  requires:
    - pip

about:
  home: https://github.com/posit-dev/py-shiny
  summary: A web development framework for Python.
  license: BSD-3-Clause AND MIT
  license_file:
    - LICENSE
    - shiny/www/shared/highlight/LICENSE
    - shiny/www/shared/showdown/license.txt
    - shiny/www/shared/jqueryui/LICENSE.txt
  description: |
    # Shiny for Python

    Shiny makes it easy to build interactive web applications with the power
    of Python’s data and scientific stack.

    - **Approachable**: Write your application in Python; no web development skills required.
    - **Flexible**: Built from the ground up to support custom layouts, styles, and the
      modularity required for full-fledged applications, all from Python.
    - **Performant**: Uses reactivity to efficiently handle data processing and minimize
      expensive re-computations.

    PyPI: [https://pypi.org/project/shiny](https://pypi.org/project/shiny)

  doc_url: https://shiny.posit.co/py/
  dev_url: https://github.com/posit-dev/py-shiny

extra:
  recipe-maintainers:
    - wch
    - sugatoray

  feedstock-name: py-{{ name|lower }}
